spring:
  application:
    name: kafkana
  server:
port: 8081
cache:
  allowed: ${ALLOW_CACHE:false}
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6389}
kafka:
  allowtopicscreation: ${ALLOW_TOPIC_CREATION:false}
  allowtopicsdeletion: ${ALLOW_TOPIC_DELETION:false}
  allowproducemessage: ${ALLOW_PRODUCING:false}
